# Generated by Django 5.1.15 on 2026-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0001_initial"),
        ("tags", "0004_remove_tag_uniq_active_shared_tag_slug_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tagassignment",
            name="uniq_assignment_per_resource_tag",
        ),
        migrations.AddField(
            model_name="tagassignment",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tagassignment",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="tagassignment",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "resource_type",
                    "resource_id",
                ],
                name="assign_scope_resource_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagassignment",
            index=models.Index(
                fields=["tenant_id", "tag", "namespace_type", "namespace_id"],
                name="assign_tenant_tag_ns_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="assignments_tagassignment_namespace_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("namespace_id__isnull", True), ("namespace_type__isnull", True)
                ),
                fields=("tenant_id", "application_id", "resource_type", "resource_id", "tag"),
                name="uniq_global_assignment_tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("namespace_id__isnull", False), ("namespace_type__isnull", False)
                ),
                fields=(
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "resource_type",
                    "resource_id",
                    "tag",
                ),
                name="uniq_ns_assignment_tag",
            ),
        ),
    ]
