# Generated by Django 5.1.15 on 2026-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "-created_at",
                ],
                name="audit_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "entity_type",
                    "entity_id",
                ],
                name="audit_scope_entity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="audit_auditlog_namespace_scope",
            ),
        ),
    ]
