# Generated by Django 5.1.15 on 2026-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serviceclientgrant",
            name="uniq_service_app_grant",
        ),
        migrations.RemoveConstraint(
            model_name="serviceclientgrant",
            name="uniq_service_tenant_grant",
        ),
        migrations.AddField(
            model_name="serviceclientgrant",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="serviceclientgrant",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="serviceclientgrant",
            name="namespace_wildcard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="serviceclientgrant",
            index=models.Index(
                fields=["tenant_id", "application_id", "namespace_type", "namespace_id"],
                name="svc_grant_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceclientgrant",
            index=models.Index(
                fields=["tenant_id", "namespace_wildcard"], name="svc_grant_wildcard_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="service_auth_serviceclientgrant_namespace_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("namespace_wildcard", False),
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    _connector="OR",
                ),
                name="svc_grant_wildcard_null_ns",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                    ("namespace_wildcard", False),
                ),
                fields=("service_client", "tenant_id", "application_id"),
                name="uniq_service_app_global_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                    ("namespace_wildcard", False),
                ),
                fields=("service_client", "tenant_id"),
                name="uniq_service_tenant_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("namespace_id__isnull", False),
                    ("namespace_type__isnull", False),
                    ("namespace_wildcard", False),
                ),
                fields=(
                    "service_client",
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                ),
                name="uniq_service_app_ns_grant",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application_id__isnull", False), ("namespace_wildcard", True)),
                fields=("service_client", "tenant_id", "application_id"),
                name="uniq_service_app_ns_wild",
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceclientgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application_id__isnull", True), ("namespace_wildcard", True)),
                fields=("service_client", "tenant_id"),
                name="uniq_service_tenant_ns_wild",
            ),
        ),
    ]
