# Generated by Django 5.1.15 on 2026-06-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_tagalias"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="uniq_active_shared_tag_slug",
        ),
        migrations.RemoveConstraint(
            model_name="tag",
            name="uniq_active_app_tag_slug",
        ),
        migrations.RemoveConstraint(
            model_name="tagalias",
            name="uniq_active_shared_alias_slug",
        ),
        migrations.RemoveConstraint(
            model_name="tagalias",
            name="uniq_active_app_alias_slug",
        ),
        migrations.RemoveConstraint(
            model_name="vocabulary",
            name="uniq_active_shared_vocab_slug",
        ),
        migrations.RemoveConstraint(
            model_name="vocabulary",
            name="uniq_active_app_vocab_slug",
        ),
        migrations.AddField(
            model_name="tag",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tagalias",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tagalias",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="namespace_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="namespace_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "type",
                    "slug",
                ],
                name="tag_scope_slug_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "is_active",
                ],
                name="tag_scope_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagalias",
            index=models.Index(
                fields=["tenant_id", "application_id", "namespace_type", "namespace_id", "slug"],
                name="alias_scope_slug_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tagalias",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "is_active",
                ],
                name="alias_scope_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vocabulary",
            index=models.Index(
                fields=["tenant_id", "application_id", "namespace_type", "namespace_id", "slug"],
                name="vocab_scope_slug_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vocabulary",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "is_active",
                ],
                name="vocab_scope_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tags_tag_namespace_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", True),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "type", "slug"),
                name="uniq_shared_global_tag_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "application_id", "type", "slug"),
                name="uniq_app_global_tag_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", False),
                    ("namespace_type__isnull", False),
                ),
                fields=(
                    "tenant_id",
                    "application_id",
                    "namespace_type",
                    "namespace_id",
                    "type",
                    "slug",
                ),
                name="uniq_app_ns_tag_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagalias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tags_tagalias_namespace_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", True),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "slug"),
                name="uniq_shared_global_alias_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "application_id", "slug"),
                name="uniq_app_global_alias_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tagalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", False),
                    ("namespace_type__isnull", False),
                ),
                fields=("tenant_id", "application_id", "namespace_type", "namespace_id", "slug"),
                name="uniq_app_ns_alias_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("namespace_id__isnull", True), ("namespace_type__isnull", True)),
                    models.Q(
                        ("application_id__isnull", False),
                        ("namespace_id__isnull", False),
                        ("namespace_type__isnull", False),
                        models.Q(("namespace_type", ""), _negated=True),
                        models.Q(("namespace_id", ""), _negated=True),
                        models.Q(("namespace_type", "global"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tags_vocabulary_namespace_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", True),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "slug"),
                name="uniq_shared_global_vocab_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", True),
                    ("namespace_type__isnull", True),
                ),
                fields=("tenant_id", "application_id", "slug"),
                name="uniq_app_global_vocab_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabulary",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("application_id__isnull", False),
                    ("is_active", True),
                    ("namespace_id__isnull", False),
                    ("namespace_type__isnull", False),
                ),
                fields=("tenant_id", "application_id", "namespace_type", "namespace_id", "slug"),
                name="uniq_app_ns_vocab_slug",
            ),
        ),
    ]
