# Generated by Django 5.1.15 on 2026-07-02 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0004_remove_tag_uniq_active_shared_tag_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name", "slug", "id"]},
        ),
        migrations.AlterModelOptions(
            name="tagalias",
            options={"ordering": ["name", "slug", "id"]},
        ),
        migrations.AlterModelOptions(
            name="vocabulary",
            options={"ordering": ["name", "slug", "id"]},
        ),
    ]
