# Generated by Django 5.2.16 on 2026-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0005_alter_tag_options_alter_tagalias_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tagalias",
            options={
                "ordering": ["name", "slug", "id"],
                "verbose_name": "tag alias",
                "verbose_name_plural": "tag aliases",
            },
        ),
        migrations.AlterModelOptions(
            name="vocabulary",
            options={
                "ordering": ["name", "slug", "id"],
                "verbose_name": "vocabulary",
                "verbose_name_plural": "vocabularies",
            },
        ),
    ]
