# Generated by Django 5.1.15 on 2026-05-26 07:45

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.CharField(max_length=100)),
                ("application_id", models.CharField(blank=True, max_length=100, null=True)),
                ("event_type", models.CharField(max_length=100)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total dispatch attempts, including the one that published it.",
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("operation_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("actor_id", models.CharField(blank=True, max_length=255, null=True)),
                ("tag_id", models.UUIDField(blank=True, null=True)),
                ("resource_type", models.CharField(blank=True, max_length=100, null=True)),
                ("resource_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "outbox_events",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at", "created_at"],
                        name="outbox_pending_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="outbox_tenant_created_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "-created_at"],
                        name="outbox_aggregate_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="outbox_type_created_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "resource_type", "resource_id", "-created_at"],
                        name="outbox_resource_idx",
                    ),
                ],
            },
        ),
    ]
