# Generated by Django 5.1.15 on 2026-07-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_outboxevent_namespace_id_outboxevent_namespace_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='recoveries',
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Times an expired processing claim was recovered (worker vanished "
                    "mid-flight; delivery outcome unknown). Re-queued for redelivery, "
                    "not counted as delivery attempts."
                ),
            ),
        ),
    ]
